# Production configuration for mount_position_monitor.py - Real observatory hardware
description: "Production configuration for mount position monitoring with real observatory hardware"

connections:
  indi_host: "192.168.100.14"
  indi_port: 7624
  mount_host: "192.168.100.73"
  mount_port: 3490

indi:
  mount:
    park_property: "10micron.TELESCOPE_PARK.PARK"
    park_setting: "On"
    coord_ra_property: "10micron.EQUATORIAL_EOD_COORD.RA"
    coord_dec_property: "10micron.EQUATORIAL_EOD_COORD.DEC"

monitoring:
  loop_sleep_seconds: 60
  park_position:
    # Expected park position based on actual mount park position (ALT/AZ coordinates)
    # ALT/AZ coordinates are fixed to horizon and don't change with sidereal time
    alt: 1.982   # Altitude in degrees - actual park position (+01:58:55.6)  
    az: 359.747  # Azimuth in degrees - actual park position (359:44:52.1)
    # Maximum allowed drift in degrees
    max_offset: 1.0

timeouts:
  indi_command: 5
  mount_command: 5
  mount_park: 60

alerting:
  # Send Mattermost alert every N seconds when corrections fail
  mattermost_interval_seconds: 60