# Production configuration for ekos_sentinel.py - Real observatory hardware
description: "Production configuration for real observatory hardware"

indi:
  weather:
    property: "Weather Meta.WEATHER_STATUS.STATION_STATUS"
    ok_setting: "Ok"
    station_indexes: [1]
  
  mount:
    park_property: "10micron.TELESCOPE_PARK.PARK"
    park_setting: "On"
    track_state_property: "10micron.TELESCOPE_TRACK_STATE.TRACK_ON"
    track_state_setting: "Off"
    coord_dec_property: "10micron.EQUATORIAL_EOD_COORD.DEC"
    coord_dec_park_position: "39"
    coord_dec_max_offset: "1"
  
  dome:
    park_property: "Dome Scripting Gateway.DOME_PARK.PARK"
    park_setting: "On"
  
  camera:
    cooler_property: "ZWO CCD ASI2600MM Pro.CCD_COOLER.COOLER_OFF"
    cooler_setting: "On"
  
  cap:
    property: null  # No dust cap in production setup
    setting: null

timeouts:
  indi_command: 5
  mount_park: 60
  roof_close: 60
  cap_close: 60

safety:
  unsafe_count_max: 3
  main_loop_sleep_seconds: 60
  max_retries: 1